### ISSUE TITLE
Change name to MOTION and MOTOR packets

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/ros_orbus_interface#26]
HASH_MOTION and HASH_MOTOR are too similar and it is easy to mismatch them.
HASH_MOTOR is OK,  I would change HASH_MOTION in HASH_CINEM or HASH_UNICYCLE as it is related to unicycle cinematic model

**Comment by rbonghi** [comment]
I think to rename in
https://github.com/officinerobotiche/or_bus_c.X/blob/develop/includes/packet/frame_motion.h

in **frame_diff_drive.h**

**Comment by rbonghi** [comment]
Fixed
