### ISSUE TITLE
Launch files?

### ISSUE THREAD

**Issue by Myzhar** [officinerobotiche/ros_orbus_interface#5]
What do you think we should do about launch files?

I was thinking about creating a new repo for each of our robots and put them there.

Another idea is to create a new repo with a basic example... then for each robot we create a branch with its own configuration.

**Comment by rbonghi** [comment]
All launch files are deleted from this repository.
An example to build your personal launch file it was written in the [README](https://github.com/officinerobotiche/ros_orbus_interface/blob/develop/README.md) file.

An other example is available on [4UDE](https://github.com/rbonghi/ros_dude)
